import = ["/home/neoorez/.config/alacritty/fonts.toml", "/home/neoorez/.config/alacritty/colorschemes/Dracula.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.80
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 24
